### ISSUE TITLE
Results of create_time_lags and pool trials depend on the order they are executed.

### ISSUE THREAD

**Issue by dmeliza** [melizalab/decoding#1]
In principle, pooling the trials before generating the hankel matrices versus after should give the same result. But they do not. Let's add a test and then figure out why it isn't working as expected.

**Comment by dmeliza** [comment]
Oops, hang on, maybe I'm mistaken about this. A test would still be good to have.

**Comment by jonahweissman** [comment]
I've added a test in  be24f8e. This probably wasn't affecting you, but I wasn't properly handling the case of presentations of the same stimulus having different recording intervals (even if the stimulus.interval was the same). The new behavior is to trim the responses to the length of the shortest interval, while continuing to crash if the trimmed array is too short to create the hankel matrix
